---
title: "For prospective Brown advisees"
author: Arman Oganisian
date: '2023-07-01'
slug: advising
categories:
  - Education
image:
  caption: ''
  focal_point: ''
output:
  blogdown::html_page:
    toc: false

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(latex2exp)
```

## Advising
Working with graduate students is a very fulfilling part of my job. Philosophically, I am not a very hierarchical person and I see students as fellow researchers working as part of a team to solve a common problem. The learning happens on the pathway towards finding these solutions and I sometimes find myself learning from students as well. I also like to foster independence, typically starting off with a lot of guidance and direction and then tapering incrementally.

I typically work with Brown University graduate students in the capacity of a thesis or dissertation adviser for the [ScM and PhD programs in Biostatistics](https://biostatistics.sph.brown.edu/academics). How many students I take on depends on availability of funding and data projects. I generally do not take on more than two new students per year. 

If you think you may like to work with me on a thesis, I first suggest you read the "Assessing Interest'' and the \ ``Finding a Project" sections below and go through some of the reading. If you feel like you are enjoying what you are reading and find it stimulating, feel free to email me to set up a meeting to discuss your interests and goals. I also summarize some placement outcomes for past advisees at the end.

## Assessing Interest

My current research interests are in causal inference for sequential (aka time-varying) treatment settings. Lately, most of the problems that have come my way deal with survival or, more generally, event-time outcomes. When it comes to methods for estimation or inference on causal effects of treatments on these survival outcomes, I tend to work within the Bayesian paradigm. Thus, working with me typically requires working at the intersection of 1) causal inference, 2) survival analysis, and 3) Bayesian methods. Projects need not involve these - for instance, I also like working on causal inference using frequentist methods when applicable or on other types of outcomes aside from survival. But generally, at least causal inference and Bayesian methods are a common thread.

In terms of computing, knowledge in a statistical programming language like R is critical. For Bayesian inference, knowledge of probabilistic programming language such as Stan is also critical. Some more elaborate Bayesian models cannot be fit in Stan and the Markov Chain Monte Carlo (MCMC) methods must be coded from scratch.

Below, I have resources for each of these topics to help you learn and gauge your own interest in these topics.

**Causal Inference**:

- [What If](https://www.hsph.harvard.edu/miguel-hernan/wp-content/uploads/sites/1268/2024/04/hernanrobins_WhatIf_26apr24.pdf)
  - Chapters 1-3: single treatment setting.
  - Chapters 11-13: Marginal structural models: estimation via IPTW estimation and g-formula.
  - Chapters 19-21: time-varying treatments.
  
**Bayesian Inference**:

- [Bayesian Data Analysis](http://www.stat.columbia.edu/~gelman/book/BDA3.pdf)
  - Chapters 1, 2, 14, and 11
- Primer on MCMC [here](https://www.cs.ubc.ca/~arnaud/andrieu_defreitas_doucet_jordan_intromontecarlomachinelearning.pdf)
- [Bayesian nonparametric data analysis](https://link.springer.com/book/10.1007/978-3-319-18968-0) - access free via Brown University library.
- A good rule of thumb is that you should be able to derive the posterior (up to a proportionality constant) for a logistic regression coefficient vector under, say, a multivariate Gaussian prior. You should also be able code a Metropolis-Hastings sampling for obtaining draws from that posterior. It's also a good way of gauging whether you like computation.


**Bayesian causal inference**:

- [Practical Introduction to Bayesian estimation of causal effects](https://onlinelibrary.wiley.com/doi/epdf/10.1002/sim.8761)
- [Bayesian Nonparametrics for Causal Inference and Missing Data](https://www.routledge.com/Bayesian-Nonparametrics-for-Causal-Inference-and-Missing-Data/Daniels-Linero-Roy/p/book/9780367341008?srsltid=AfmBOooQdwAQGPuRQ3aKSf_rdO_es0NP_ijM3bR0Q1l4JPQrcrnF7_8U)
- [Causal Inference: A Missing Data Perspective
](https://projecteuclid.org/journals/statistical-science/volume-33/issue-2/Causal-Inference-A-Missing-Data-Perspective/10.1214/18-STS645.full)
- [Bayesian causal inference: a critical review](https://royalsocietypublishing.org/doi/10.1098/rsta.2022.0153)

**Survival outcomes**:

- Bayesian causal inference with survival outcomes see [here](https://arxiv.org/abs/2310.12358):
- [Bayesian Survival Analysis](https://link.springer.com/book/10.1007/978-1-4757-3447-8) by Ibrahim. Available via Brown University library. See Chapters 1,2, and 3.


## Finding a Project

Though it can happen many ways, typically a a thesis advising position has arisen in these ways for me:

- A student approaches me and has read some of the literature in the "Assessing Interest" section in detail and concluded they are interested in working in this area. If I have an appropriate project that can be completed within 1-1.5 years ready, I will offer this project as a thesis project for the student. If I do not have a project ready, I will keep the student in mind for when an appropriate project does come my way.

- A student approaches me usually after having done a previous RA-ship working with data. They are very interested in, say, a causal (or Bayesian) extension of the analysis and would like me to supervise. This is an example of a student coming to me with a project, which does sometimes happen and which I like because it can expose me to new and interesting problems.

My work is very application-driven. I'm quite bad at (and generally do not enjoy) making up methodological problems to solve and. Instead, I generate research ideas by working with clinical and applied collaborators in, say, the Department of Epidemiology or the medical school on concrete data analysis. Over the course of working on these projects, I often notice complexities for which I find existing methods to be unsatisfactory or have shortcomings. This then motivates new methodological research to overcome these shortcomings. Thesis work often arises from these concrete data analyses projects with collaborators - the arrival of these projects and their appropriateness for thesis work is stochastic in nature. I may not have an appropriate project lined up when you approach me. If I do not, you should keep searching for other projects and not assume one will pop up in the meantime.

## Current Students and Past Placements
Below are previous students, degree completed, year of completion, and first industry or academic placement after graduation. Brown archives completed ScM theses [here](https://repository.library.brown.edu/studio/search/?q=biostatistics&selected_facets=ir_collection_name%3ABiostatistics). I recommend prospective advisees read through some of the theses from my former students to get a sense of the type of projects they can work on.

- Current Students
  - Daniel Posmik, PhD 2029.
  - Esteban Fernandes-Morales, PhD 2026.
  - Zhaoxiang Ding, ScM 2025.

- Previous Students
  -   Zihan Zhou, ScM 2024 - Biostatistics PhD student @ Pennsylvania State University.
  - Tova Ibbotson, ScM 2024 - Senior Statistician @ GSK.
  - Nancy Liu, ScM 2023 - Biostatistician @ Rutgers University.
  - Anthony Girard, ScM 2023 - Statistical Analyst @ Leonard Davis Institute, University of Pennsylvania.

